[package]
name = "gossip"
version = "0.4.90-unstable"
description = "A social media client for nostr"
authors = ["Mike Dilger <mike@mikedilger.com>", "fiatjaf <fiatjaf@gmail.com>", "Nate Levin <natelevincycling@gmail.com>", "Nethanja Focking <nethanja@nethanja.de>", "Daniele Tonon <tonon@vitamino.it>", "jeremyd (@jeremyd)"]
license = "MIT"
repository = "https://github.com/mikedilger/gossip"
homepage = "https://github.com/mikedilger/gossip"
default-run = "gossip"
edition = "2021"

[features]
default = ["rustls-tls"]
lang-cjk = []

native-tls = [ "reqwest/native-tls", "tungstenite/native-tls", "tokio-tungstenite/native-tls"]
rustls-tls = [ "reqwest/rustls-tls", "tungstenite/rustls-tls-webpki-roots", "tokio-tungstenite/rustls-tls-webpki-roots"]

[dependencies]
async-recursion = "1.0"
async-trait = "0.1"
base64 = "0.21"
dashmap = "5.4"
dirs = "4.0"
eframe = { git = "https://github.com/mikedilger/egui", rev = "4687a41b1af79be89181a45d35163090b5556e53", features = [ "dark-light", "persistence" ] }
egui-winit = { git = "https://github.com/mikedilger/egui", rev = "4687a41b1af79be89181a45d35163090b5556e53", features = [ "default" ] }
egui_extras = { git = "https://github.com/mikedilger/egui", rev = "4687a41b1af79be89181a45d35163090b5556e53", features = [ "image", "svg", "tracing" ] }
encoding_rs = "0.8"
fallible-iterator = "0.2"
futures = "0.3"
futures-util = "0.3"
gossip-relay-picker = "0.1"
hex = "0.4"
http = "0.2"
humansize = "2.1"
image = { version = "0.24", features = [ "png", "jpeg" ] }
lazy_static = "1.4"
linkify = "0.9"
memoize = "0.4"
mime = "0.3"
nostr-types = "0.4"
parking_lot = "0.12"
qrcode = { git = "https://github.com/mikedilger/qrcode-rust", rev = "519b77b3efa3f84961169b47d3de08c5ddd86548" }
r2d2 = "0.8"
r2d2_sqlite = "0.21"
rand = "0.8"
regex = "1.7"
reqwest = { version = "0.11", default-features=false, features = ["brotli", "deflate", "gzip", "json"] }
rusqlite = { version = "0.28", features = ["bundled", "chrono", "serde_json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
thiserror = "1.0"
time = { version = "0.3", features = [ "formatting" ] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "std", "env-filter" ] }
tokio-tungstenite = { version = "0.18", default-features = false, features = [ "connect", "handshake" ] }
tungstenite = { version = "0.18", default-features = false }
zeroize = "1.5"

# Force scrypt to build with release-like speed even in dev mode
[profile.dev.package.scrypt]
opt-level = 3
debug-assertions = false
overflow-checks = false

[package.metadata.deb]
section = "web"
assets = [
    ["target/release/gossip", "/usr/bin/", "755"],
    ["packaging/debian/gossip.desktop", "/usr/share/applications/gossip.desktop", "644"],
]
