[package]
name = "gossip"
version = "0.6.0"
description = "A social media client for nostr"
authors = ["Mike Dilger <mike@mikedilger.com>", "fiatjaf <fiatjaf@gmail.com>", "Nate Levin <natelevincycling@gmail.com>", "Nethanja Focking <nethanja@nethanja.de>", "Daniele Tonon <tonon@vitamino.it>", "jeremyd (@jeremyd)"]
license = "MIT"
repository = "https://github.com/mikedilger/gossip"
homepage = "https://github.com/mikedilger/gossip"
default-run = "gossip"
edition = "2021"

[features]
default = ["rustls-tls"]
lang-cjk = []

native-tls = [ "reqwest/native-tls", "tungstenite/native-tls", "tokio-tungstenite/native-tls"]
rustls-tls = [ "reqwest/rustls-tls", "tungstenite/rustls-tls-webpki-roots", "tokio-tungstenite/rustls-tls-webpki-roots"]

[dependencies]
async-recursion = "1.0"
async-trait = "0.1"
base64 = "0.21"
dashmap = "5.4"
dirs = "5.0"
eframe = { git = "https://github.com/mikedilger/egui", rev = "a18ee5e5867afb7c80c8cd0bc2815278274124b3", features = [ "persistence" ] }
egui-winit = { git = "https://github.com/mikedilger/egui", rev = "a18ee5e5867afb7c80c8cd0bc2815278274124b3", features = [ "default" ] }
egui_extras = { git = "https://github.com/mikedilger/egui", rev = "a18ee5e5867afb7c80c8cd0bc2815278274124b3", features = [ "image", "svg" ] }
encoding_rs = "0.8"
fallible-iterator = "0.2"
futures = "0.3"
futures-util = "0.3"
gossip-relay-picker = { git = "https://github.com/mikedilger/gossip-relay-picker", rev = "4648e7b6dc74e52df0a7cc00a5814f689a8a9d3c" }
hex = "0.4"
http = "0.2"
humansize = "2.1"
image = { version = "0.24", features = [ "png", "jpeg" ] }
lazy_static = "1.4"
linkify = "0.9"
memoize = "0.4"
mime = "0.3"
nostr-types = { git = "https://github.com/mikedilger/nostr-types", rev = "3066f3dbe95c98ce5527777412db289b266d1f4a" }
parking_lot = "0.12"
qrcode = { git = "https://github.com/mikedilger/qrcode-rust", rev = "519b77b3efa3f84961169b47d3de08c5ddd86548" }
rand = "0.8"
regex = "1.8"
reqwest = { version = "0.11", default-features=false, features = ["brotli", "deflate", "gzip", "json"] }
rusqlite = { version = "0.29", features = ["bundled", "chrono", "serde_json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
time = { version = "0.3", features = [ "formatting", "macros" ] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "std", "env-filter" ] }
tokio-tungstenite = { version = "0.18", default-features = false, features = [ "connect", "handshake" ] }
tungstenite = { version = "0.18", default-features = false }
vecmap-rs = "0.1"
zeroize = "1.6"

# Force scrypt to build with release-like speed even in dev mode
[profile.dev.package.scrypt]
opt-level = 3
debug-assertions = false
overflow-checks = false

[package.metadata.deb]
section = "web"
assets = [
    ["target/release/gossip", "/usr/bin/", "755"],
    ["packaging/debian/gossip.desktop", "/usr/share/applications/gossip.desktop", "644"],
]
