[package]
name = "gossip"
version = "0.12.0-unstable"
description = "A social media client for nostr"
authors = ["Mike Dilger <mike@mikedilger.com>", "fiatjaf <fiatjaf@gmail.com>", "Nate Levin <natelevincycling@gmail.com>", "Nethanja Focking <nethanja@nethanja.de>", "Daniele Tonon <tonon@vitamino.it>", "jeremyd (@jeremyd)"]
license = "MIT"
repository = "https://github.com/mikedilger/gossip"
homepage = "https://github.com/mikedilger/gossip"
default-run = "gossip"
edition = "2021"

[features]
default = [ "rustls-tls-native" ]
lang-cjk = [ "gossip-lib/lang-cjk" ]
video-ffmpeg = [ "egui-video", "sdl2" ]
native-tls = [ "gossip-lib/native-tls" ]
rustls-tls = [ "gossip-lib/rustls-tls" ]
rustls-tls-native = [ "gossip-lib/rustls-tls-native" ]
appimage = [ "gossip-lib/appimage" ]

[dependencies]
bech32 = "0.11"
eframe = { git = "https://github.com/bu5hm4nn/egui", rev = "521b087269acb6032d5040fa8bad33e84dbadede", features = [ "persistence", "wayland", "wgpu" ] }
egui-winit = { git = "https://github.com/bu5hm4nn/egui", rev = "521b087269acb6032d5040fa8bad33e84dbadede", features = [ "default" ] }
egui_extras = { git = "https://github.com/bu5hm4nn/egui", rev = "521b087269acb6032d5040fa8bad33e84dbadede", features = [ "syntect" ] }
## egui = { git = "https://github.com/bu5hm4nn/egui", rev = "521b087269acb6032d5040fa8bad33e84dbadede", features = [ "deadlock_detection" ] }
egui-video = { git = "https://github.com/bu5hm4nn/egui-video", rev = "21005df83139d0a7bdc910c66df3bc5a7b7bade2",  features = [ "from_bytes" ], optional = true }
gossip-relay-picker = { git = "https://github.com/mikedilger/gossip-relay-picker", rev = "3ea9ccfc641cdef1574a3c054a086ac2e24d3c4a" }
gossip-lib = { path = "../gossip-lib" }
humansize = "2.1"
image = { version = "0.24.6", features = [ "png", "jpeg" ] }
lazy_static = "1.4"
memoize = "0.4"
nostr-types = { git = "https://github.com/mikedilger/nostr-types", rev = "d09019261b6d57722eaeb006dd768bd6207c41d1", features = [ "speedy" ] }
paste = "1.0"
qrcode = { git = "https://github.com/mikedilger/qrcode-rust", rev = "519b77b3efa3f84961169b47d3de08c5ddd86548" }
resvg = "0.35.0"
rpassword = "7.2"
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", rev = "f2f1e29a416bcc22f2faf411866db2c8d9536308", features = ["bundled"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3", features = [ "formatting", "macros" ] }
tiny-skia = "0.10.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "std", "env-filter" ] }
url = "2.5"
usvg = "0.35.0"
zeroize = "1.7"
chrono = ">=0.4.37"

[package.metadata.deb]
section = "web"
assets = [
    ["target/release/gossip", "/usr/bin/", "755"],
    ["../packaging/debian/gossip.desktop", "/usr/share/applications/gossip.desktop", "644"],
]
features = [ "lang-cjk" ]

[package.metadata.appimage]
auto_link = true
